# -*- coding: utf-8 -*-
"""Tarefa1 - Projeto Integrador 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SUeABJ6r7fg0dS2-q_PyuKBU4LR0BBaX

Criar um script que imprima uma tabela de conversão de polegadas para centímetros.
Deseja-se que na tabela conste valores desde 1 polegada até 20 polegadas inteiras.
"""

# Eu sei que poderia ser mais simples, estou inventando para aprender outras coisas!!!
import pandas as pd

pol = list(range(1,11))
cm = [x * 2.54 for x in pol]
dados = {'Polegadas': pol, 'Centimetros': cm}
df = pd.DataFrame(dados)

df

"""Criar um algoritmo que leia um número que servirá para controlar os números pares que serão impressos a partir de 2.

Exemplo:
Quantos: 4           Saída: 2 4 6 8
"""

# Eu sei que poderia ser mais simples, estou inventando para aprender outras coisas!!!
while True:
  qtd = input('\nQuantidade de números pares impressos (s = parar script): ')

  if (qtd == 's'):
    break
  else:
    try:
      int(qtd)
      for i in range(2, (int(qtd) + 1) * 2, 2):
          print(i, end = " / ")
    except ValueError:
      print('\nDigite um n° inteiro!!!')

"""Criar um algoritmo que leia a quantidade de números que se deseja digitar para
que possa ser impresso o maior e o menor numero digitados Não suponha que
todos os números lidos serão positivos.
"""

# Eu sei que poderia ser mais simples, estou inventando para aprender outras coisas!!!
lista = []

def validaEntrada(qtd):
  try:
    qtd = int(qtd)
    return True
  except ValueError:
    return False

def addVal(qtd):
  qtd = int(qtd)
  cont = 1

  while qtd > 0:
    num = input(f'Digite o {cont}° número da lista: ')

    try:
      lista.append(int(num))
      qtd -= 1
      cont += 1
    except:
      print('\nDigite um n° inteiro!\n')

  return print(f'---\nValor mínimo: {min(lista)}\nValor máximo: {max(lista)}')

# Script ---
while True:
  qtd = input('Qtd. de números que deseja add. na lista (s = parar script): ')

  if(qtd == 's'):
    print('- FIM -')
    break
  elif(validaEntrada(qtd) == False):
    continue
  elif(validaEntrada(qtd) == True):
    addVal(qtd)
    break

"""Entrar com nome, nota da PR1 e nota da PR2 de 15 alunos. Imprimir uma listagem,
contendo: nome, nota da PR1, nota da PR2 e média arredondada de cada
aluno Ao final calcule a media geral da turma.
"""

# Eu sei que poderia ser mais simples, estou inventando para aprender outras coisas!!!
import pandas as pd

cont = 1
qtd_alunos = 15
lsNome, lsPR1, lsPR2, lsMedia = [], [], [], []
dfSala = pd.DataFrame(columns=['Nome', 'PR1', 'PR2', 'Media']);

def montarRegistros(dfSala, lsNome, lsPR1, lsPR2, lsMedia):
  newRows = [pd.DataFrame({
    'Nome': lsNome,
    'PR1': lsPR1,
    'PR2': lsPR2,
    'Media': lsMedia
  })]

  return newRows

for cont in range(1, qtd_alunos+1):
  lsNome.append(input(f'Digite o nome da(o) {cont}° aluna(o): ').capitalize())
  lsPR1.append(float(input('Digite o valor da prova 1: ')))
  lsPR2.append(float(input('Digite o valor da prova 2: ')))
  lsMedia.append(round((lsPR1[-1] + lsPR2[-1]) / 2, 0))
  print('---------------------------------')
  cont += 1

registros = montarRegistros(dfSala, lsNome, lsPR1, lsPR2, lsMedia)
dfSala = pd.concat([dfSala] + registros, ignore_index = True)
media_geral = dfSala['Media'].mean()

print(f'\n A média geral da sala foi: {round(media_geral, 2)}')

dfSala.head(qtd_alunos)