# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jLShlRUe60Sghn_2K5Rwzsh4TEhh1X6m
"""



"""•Desafio 1: crie um script em Python que receba o nome de uma
pessoa e apareça a seguinte mensagem: Olá
<<nome_digitado>> seja bem vindo a Fatec Ourinhos! negrito
"""

nome=input('Digite seu nome: ')
print('Ola', nome, 'seja bem vindo a Fatec Ourinhos!')

"""•Desafio 2: crie um script em Python que receba o dia, o mês e o
ano de nascimento de uma pessoa, separadamente. Deve exibir no
final a seguinte mensagem: Você nasceu no dia
<<dia_digitado>>, do mês <<mês_digitado>> no ano
<<ano_digitado>>!
"""

dia=input('Digite o dia de nascimento: ')
mes=input('Digite o mês de nascimento: ')
ano=input('Digite o ano de nascimento: ')

print('voce nasceu no dia', dia, 'do mes', mes, 'no ano', ano)

"""•Desafio 3: crie um script em Python que receba dois números e
exiba a soma entre eles.
"""

num1 = input('digite um numero: ')
num2 = input('digite outro numero: ')

soma = int(num1) + int(num2)

print('A soma dos dois numeros digitados e:', soma)

"""Receba dois números inteiros, faça e exiba o resultado das operações matemáticas básicas (+,-,*,/)."""

num1 = int(input('digite um numero: '))
num2 = int(input('digite outro numero: '))

soma = num1 + num2
multiplica = num1 * num2
divisao = num1 / num2
subtracao = num1 - num2

print('soma:', soma, 'subtracao:', subtracao, 'multiplicacao:', multiplica, 'divisao:', divisao)

"""Receba dois números inteiros, faça e exiba: a potência entre os dois números, o resto da divisão entre os dois números e a divisão inteira
entre os dois números.
"""

num1 = int(input('digite um numero: '))
num2 = int(input('digite outro numero: '))

potencia = num1 ** num2
resto = num1 % num2
div_int = num1 // num2

print('potencia:', potencia, 'resto da divisao:', resto, 'divisao inteira:', div_int)

"""Receba um número inteiro e calcule sua raiz quadrada e sua raiz cúbica."""

num1 = int(input('digite um numero: '))

raiz_quad = num1 ** 1/2
raiz_cub = num1 ** 1/3

print('raiz quadrada:', raiz_quad, 'raiz cubica:', raiz_cub)

"""Teste o seguinte trecho de código abaixo e verifique as formas diferentes de saídas:
nome=input('Digite seu nome: ')
print(f"Bem vindo {nome}!")
print(f"Bem vindo {nome:20}!")
print(f"Bem vindo {nome :>20}!")
print(f"Bem vindo {nome:<20}!")
print(f"Bem vindo {nome:^20}!")
print(f"Bem vindo {nome:=^20}!")
"""

nome=input('Digite seu nome: ')
print(f"Bem vindo {nome}!")
print(f"Bem vindo {nome:20}!")
print(f"Bem vindo {nome :>20}!")
print(f"Bem vindo {nome:<20}!")
print(f"Bem vindo {nome:^20}!")
print(f"Bem vindo {nome:=^20}!")

"""Faça um script que receba um valor de temperatura em Fahrenheit e converta-o para Celsius. Fórmula de conversão C = (F – 32) * (5 / 9)."""

num1 = int(input('digite a temperatura em fahrenheit: '))
celsius = (num1 - 32) * (5/9)
print('a temperatura em celsius e:', celsius)

"""Faça um script que calcule o valor de uma função de primeiro grau do tipo AX + B = 0."""

a = float(input("Digite o valor de A: "))
b = float(input("Digite o valor de B: "))

x = -b/a

print("O valor de X é:", x)

"""A imobiliária Imóbilis vende apenas terrenos retangulares. Faça um script em Python para ler as dimensões de um terreno e
depois exibir a área do terreno.
"""

base = float(input('digite a base em metros: '))
altura = float(input('digite a altura em metros: '))

area = base * altura

print('A area do terreno em metros e:', area)

"""Faça um script em Python para calcular quantas ferraduras são necessárias para equipar todos os cavalos comprados para
um haras.
"""

cavalos = int(input('Digite o número de cavalos que o haras possui: '))

ferraduras = cavalos * 4

print('o numero de ferraduras necessarias e:', ferraduras)

"""A padaria Hotpão vende uma certa quantidade de pães franceses e uma quantidade de broas a cada dia. Cada pãozinho
custa R$ 0,12 e a broa custa R$ 1,50. Ao final do dia, o dono quer saber quanto arrecadou com a venda dos pães e broas
(juntos), e quanto deve guardar numa conta de poupança (10% do total arrecadado). Você foi contratado para fazer os cálculos
para o dono. Com base nestes fatos, faça um script em Python para ler as quantidades de pães e de broas, e depois calcular os
dados solicitados.
"""

paes = float(input('digite a quantidade de paes: '))
broas = float(input('digite a quantidade de broas: '))

paes_total = paes * 0.12
broas_total = broas * 1.5
total = paes_total + broas_total
poupanca = total * 0.1

print('valor total vendido:', total, 'valor para guardar:', poupanca)

"""Escreva um script em Python para ler o nome e a idade de uma pessoa, e exibir quantos dias de vida ela possui. Considere
sempre anos completos, e que um ano possui 365 dias. Ex: uma pessoa com 19 anos possui 6935 dias de vida; veja um
exemplo de saída: MARIA, VOCÊ JÁ VIVEU 6935 DIAS
"""

nome = input('Digite o seu nome: ')
idade = int(input('digite a sua idade em anos: '))

dias_vividos = idade * 365

print(nome + ',', 'você já viveu', dias_vividos, 'dias')

"""Um motorista deseja colocar no seu tanque X reais de gasolina. Escreva um script em Python para ler o preço do litro da
gasolina e o valor do pagamento, e exibir quantos litros ele conseguiu colocar no tanque.
"""

gasolina = float(input('digite o preco do litro da gasolina: '))
dinheiro = float(input('valor que deseja comprar de gasolina: '))

litros = dinheiro / gasolina

print('voce abasteceu', litros, 'de gasolina.')

"""O restaurante a quilo Bem-Bão cobra R$12,00 por cada quilo de refeição. Escreva um script em Python que leia o peso do
prato montado pelo cliente (em quilos) e imprima o valor a pagar. Assuma que a balança já desconte o peso do prato.
"""

peso = float(input('digite o peso total do prato (em gr) de comida: '))

pagar = peso * 12

print('voce deve pagar: R$', pagar)