# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIzGCQ_9gI1DTUDQiRGW71x54K2Mripb
"""



"""Criar um script que imprima uma tabela de conversão de polegadas para centímetros. Deseja-se que na tabela conste valores desde 1 polegada até 20 polegadas inteiras."""

for cont in range(1,21):
  print(f'{cont} in = {cont*2.54} cm')

"""Criar um algoritmo que leia um número que servirá para controlar os números pares que serão impressos a partir de 2. Exemplo:

Quantos: 4 Saída: 2 4 6 8
"""

x=int(input('Digite quantos pares quer: '))
for cont in range(2,(x*2+1),2):
  print(cont)

"""Criar um algoritmo que leia a quantidade de números que se deseja digitar para que possa ser impresso o maior e o menor numero digitados Não suponha que todos os números lidos serão positivos."""

Lista=[]
q=int(input('Digite quantos números quer digitar: '))
for cont in range(1, q+1 ):
   v=int(input(f'Digite o {cont}° número: '))
   Lista.append(v)

print(f"O maoir número é {max(Lista)} e o menor é {min(Lista)}")

"""Entrar com nome, nota da PR1 e nota da PR2 de 15 alunos. Imprimir uma listagem, contendo: nome, nota da PR1, nota da PR2 e média arredondada de cada aluno Ao final calcule a media geral da turma."""

1t= 0
Sala=[]
for cont in range(1, 16):
  nome=input(f'Digite o nome da(o) {cont}° aluna(o):')
  pr1=float(input('Digite o valor da prova 1: '))
  pr2=float(input('Digite o valor da prova 2: '))
  x=(f'Aluna(o) {nome} tirou {pr1} na 1° e {pr2} na 2° ficando com {round((pr1 + pr2)/2 , 1)} de média.')
  t= t + pr1+pr2
  Sala.append(x)

for item in Sala:
  print(item)

print(f'A média da turma foi {round(t/30 , 1)}')